name: Ansible CI

on: [push]

jobs:

  ansible_lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'input'

    - uses: actions/checkout@v2
      with:
        repository: 'sebthebert/MyAnsibleCI'
        path: 'output' 

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} 

    - name: Pull Docker image
      run: docker pull $DOCKER_IMG
      env:
        DOCKER_IMG: docker.pkg.github.com/ansibleci/docker-img-ansible/ansibleci:0.0.2

    - name: Run image
      run: docker run --rm -t --name ansible_lint -v $GITHUB_WORKSPACE/input:/input -v $GITHUB_WORKSPACE/output:/output $DOCKER_IMG ansible-playbook ansible-lint.yml
      env:
        DOCKER_IMG: docker.pkg.github.com/ansibleci/docker-img-ansible/ansibleci:0.0.2

    - name: print results
      run: ls -lR $GITHUB_WORKSPACE

    - name: git commit and push to 'sebthebert/MyAnsibleCI'
      run: |
        cd $GITHUB_WORKSPACE/output
        git config --local user.email "sebthebert@github.com"
        git config --local user.name "Sebastien Thebert"
        git add -A
        git commit -m "AnsibleCI update for commit '${{github.sha}}' on '${{github.repository}}'"
        git push --force https://${{secrets.PAT_REPOS_ADMIN}}@github.com/sebthebert/MyAnsibleCI.git master
  
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        directory: /home/runner/work/ansible-role-demo/ansible-role-demo/output
#        force: yes  
#        github_token: ${{secrets.PAT_ANSIBLECI_RW}}
#        repository: "AnsibleCI/MyAnsibleCI"
#      run: git push --force https://${{secrets.PAT_ANSIBLECI_RW}}@github.com/AnsibleCI/MyAnsibleCI.git master 
